### ISSUE TITLE
CI/CD use case

### ISSUE THREAD

**Issue by szuecs** [merklecounty/rget#14]
From the [description](https://github.com/merklecounty/rget/blob/master/README.md#github-developer-usage) it looks like it was not really thought about CI/CD use case. 
Every reasonable project should have it automated, but the manual challenge seems to break the use case.
Maybe there’s documentation missing?

**Comment by philips** [comment]
This is a case of missing documentation.

All of rget's builds are automated; and I do not actually use the `rget github publish-release-sums` subcommand myself on this project.

Instead I use goreleaser which generates the SHA256SUM and then call `rget submit $URL-TO-SHA256SUMS-ON-GITHUB`. 

See https://github.com/merklecounty/rget/blob/master/.goreleaser.yml#L30 and https://github.com/merklecounty/rget/blob/master/Documentation/integrations.md

I will put up a README PR to try and address this.

**Comment by philips** [comment]
PTAL https://github.com/merklecounty/rget/pull/16
